OS: OSX
osx_image: xcode11.2
language: swift
script: xcodebuild clean build test -workspace FizzBuzz.xcodeproj/project.xcworksp
ace -scheme "FizzBuzz" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.2.2,name=iPhone 11
 Pro Max" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
